Numpy Array Operation

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic slicing ", arr[2:7])
print("With steps", arr[1:8:2])
print("Nagative indexing ", arr[-3])

Basic slicing  [3 4 5 6 7]
With steps [2 4 6 8]
Nagative indexing  8


## 2D Array

In [6]:
arr_2d = np.array([[1,2,3],
                  [3,4,5],
                  [6,7,8]])
print("Specific Element ", arr_2d[1, 2])
print("Entire row : ", arr_2d[1])
print("Colimn target : ", arr_2d[:,1])

Specific Element  5
Entire row :  [3 4 5]
Colimn target :  [2 4 7]


## Sorting 

In [11]:
unsorted = np.array([3, 1, 4, 7, 9, 2])
print("Sorted Array : ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted  2D Array by column ", np.sort(arr_2d_unsorted, axis=0))

Sorted Array :  [1 2 3 4 7 9]
Sorted  2D Array by column  [[1 1]
 [2 2]
 [3 3]]


## Filtering 

In [12]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even Numbers", even_number)

Even Numbers [ 2  4  6  8 10]


Filter With Mask

In [13]:
mask = numbers >5
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


## Fancy Indexing np.where 

In [ ]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where ", numbers[where_result])

[1 3 5]
NP where  [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers >5 , numbers *2 , numbers)
print(condition_array) 

[ 1  2  3  4  5 12  7 16  9 20]


## Adding And Removing data

In [22]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## Array Comapatibility

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility shapes : ", a.shape == b.shape)

Compatibility shapes :  True


Comapatibility Shapes False

In [29]:
original = np.array([[1,2], [3, 4]])
new_row = np.array([[5, 6], [7, 8]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With New Column : ", with_new_col)



[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
With New Column :  [[1 2 7]
 [3 4 8]]


In [32]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array After deletion ", deleted)

Array After deletion  [1 2 4 5]
