In [3]:
import numpy as np

In [14]:
arr_1d = np.array([1,2,3,4,5])
print("1D Array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2d)

1D Array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


## List vs Array

In [19]:
py_list = [1,2,3]
print("Python List multiplication", py_list *2)



np_array  = np.array([1,2,3])
print("Python array multiplication ", np_array * 2)


import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time ", time.time() - start)


start = time.time()
np_array = np.arange(1000000) *2
print("\n Numpy operation time: ", time.time() - start)


Python List multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time  0.12483811378479004

 Numpy operation time:  0.007062196731567383


## Creating array from scrach 

In [ ]:
zeros = np.zeros((3,4))
ones = np.ones((3,4))
print("zeros arrray: \n", zeros)
print("ones arrray: \n", ones)

full = np.full((2,2), 7)
print("full arrray: \n", full)

random  = np.random.random((2,3)) * 10
print("Random arrray: \n", random)

sequence = np.arange(0, 11, 2)
print("Sequience arrray: \n", sequence)



zeros arrray: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones arrray: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full arrray: 
 [[7 7]
 [7 7]]
Random arrray: 
 [[5.25173806 0.99333175 6.82029182]
 [3.2868716  8.89788984 5.39400643]]
Sequience arrray: 
 [ 0  1  2  3  4  5  6  7  8  9 10]


## vector , Matrics  tensor 

In [39]:
vector  = np.array([1, 2, 3])
print("Vector ", vector)

## Two dimentional array
matrix  = np.array([[1, 2, 3],
                    [4, 5, 6]])

print("matrix: ", matrix)

## tensor 
tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])

print("Tensor : ", tensor)

Vector  [1 2 3]
matrix:  [[1 2 3]
 [4 5 6]]
Tensor :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Aray properties 

In [40]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape :", arr.shape)
print("Shape :", arr.ndim)
print("Shape :", arr.size)
print("Shape :", arr.dtype)

Shape : (2, 3)
Shape : 2
Shape : 6
Shape : int64


## Array Reshaping 

In [ ]:
arr =np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened Array", flattened)

# revel (return view , insted of copy)
reveled = reshaped.ravel()
print("\n Reveled ", reveled)

# Transpose 

transpose = reshaped.T
print("\n Transpose ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reveled  [ 0  1  2  3  4  5  6  7  8  9 10 11]
